"""Standard error type constants.

All error types use UPPER_SNAKE_CASE format for consistency.
These constants should be used in error_response() calls.
"""

# General errors
INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
INVALID_REQUEST = "INVALID_REQUEST"
VALIDATION_ERROR = "VALIDATION_ERROR"
RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND"
UNAUTHORIZED = "UNAUTHORIZED"
FORBIDDEN = "FORBIDDEN"
CONFLICT = "CONFLICT"

# Validation errors
MISSING_FIELDS = "MISSING_FIELDS"
INVALID_FORMAT = "INVALID_FORMAT"
INVALID_VALUE = "INVALID_VALUE"

# Business logic errors
INSUFFICIENT_BALANCE = "INSUFFICIENT_BALANCE"
POSITION_LIMIT_EXCEEDED = "POSITION_LIMIT_EXCEEDED"
MARKET_CLOSED = "MARKET_CLOSED"
INVALID_TRADE = "INVALID_TRADE"

# Resource-specific errors
MODEL_NOT_FOUND = "MODEL_NOT_FOUND"
PROVIDER_NOT_FOUND = "PROVIDER_NOT_FOUND"
TRADE_NOT_FOUND = "TRADE_NOT_FOUND"

# External service errors
EXTERNAL_SERVICE_ERROR = "EXTERNAL_SERVICE_ERROR"
API_KEY_INVALID = "API_KEY_INVALID"
RATE_LIMIT_EXCEEDED = "RATE_LIMIT_EXCEEDED"
API_ACCESS_DENIED = "API_ACCESS_DENIED"
API_ENDPOINT_NOT_FOUND = "API_ENDPOINT_NOT_FOUND"
CONNECTION_ERROR = "CONNECTION_ERROR"
REQUEST_TIMEOUT = "REQUEST_TIMEOUT"
UNKNOWN_RESPONSE_FORMAT = "UNKNOWN_RESPONSE_FORMAT"
NO_MODELS_FOUND = "NO_MODELS_FOUND"

# Network/URL validation errors
INVALID_URL_SCHEME = "INVALID_URL_SCHEME"
INVALID_HOSTNAME = "INVALID_HOSTNAME"
PRIVATE_ADDRESS_REJECTED = "PRIVATE_ADDRESS_REJECTED"

# System errors
DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE"
UPDATE_CHECK_FAILED = "UPDATE_CHECK_FAILED"
SETTINGS_UPDATE_FAILED = "SETTINGS_UPDATE_FAILED"
